dist: trusty
sudo: false
language: node_js
node_js: node
cache: yarn

deploy:
  on:
    tags: true
  skip_cleanup: true
  provider: cloudfoundry
  username:
    secure: eJLpJbkHBtrU0/mrJc23VWkSHb1NwOxGD31rBV2TkEcOArarWHOfUKTV5kzpkAG5Wlr2kNJGxmyptPlj9KvHx/1m5W4bXxwxbZx+UMBvrPNaESdg98nJ/j9v4F17wvv+i2bhx/1o7kv/8KYKbayBeKx9FAfHMppWXXYDo6CsvSWd8K3k+dr0EmL+6Yj3ljqK8xpglyVdavsA5Wt8v7hoOjwnLydpv7NbP7U3TYgC36tTGMNXk4jh34jfQ6h9n72Jxl3q5GyrcIrpvxpNAyPXd69wCeQDZ/o/kous9ZsxgA9H4eMzZfVa6SOZS7SD2fmVU+ZaYwTLn8UpphWOoV8ukRk3tsFZCX5nH1cyC05gJYUvama6PaZmia/wM/jtHrXV9LJtCeKaLKx4yVI+IMoWrMRrTKRgt47KMAW3hPRDPIMrTPAeU7ZJF4bnPf88pyaWGDp8n5OOa8rflP9APFAw/O5K5oqFM2iFY/SyNJLDvWon0PpcY74RdF3W8Oa4OB33fI4yH+xhnZ5MDLmFthnHJjWiNkrMM4Zx7B8VvzOKx/7KN+X0yEStGSD766U/gWDpNUE8DnSNVA0p7UBkLwzZ+OkU5uwbTlbteazmjncLcZmRseVOGSRvow58xBSrSc4a0xFmm4uSI/Qnk3rsjzKjDjmiE3ctammh6DbotVqKx5I=
  password:
    secure: MGEtOs0tBeELMK3XppFM2lXA5a6ZoVNkueRoHtyc0oV9c2tuKImcVVjOL8Y9+B+HMy/3/6bc8uOMB0nrSEqdlH7abFFn3ymizbnG+G1nXFW6xQDPmu74UAOUFgDRsGQDksPGRsVrTvDK5x4WiCy51NgWIBp/KCiJvZAdKsHEpbQtxFEfCu7qdOxZvJUoeTPKgw1AoJuZjW2QjosTHVldzhIpEX2Ut+3rzQ6WM97p4B4OhsM8rAQPxCIR9uLMiaJWgl+eRQanHq/GMS+cnlgxdN4vf7zlCOvo2nk5+Ui6C6I+2sq8j9WdPkGWpC1QywrrdoiQGqb4e5CnsCzXFh3mrpQ5CjGET2UtP1LcBtYcJBLOobVVQedsuIfl2xhxExkSeKde9VeTH5glpjgwjqOAFRrciiLlYnrUiUBnmLSYfDGycMINtzrivbUvgsVsW8zGYunwZw4l+CajHcr44hvDFUmc6GoC3QCS12sbXppPpR8PhDEULQkNFND7wklQhl0VCJTKHQLSdS6OiSdqHqTvABI34KXftumvJsQklQh23rbhYUzQTU43y9CDLniMLiDRtnxQnz/nUs6HmxMmr8WqUbz3GJwnvEZR935AgzujfRtFt3iOnnj4noY+bq8t4pnHpWSQdKMIEswBwvU0AvWkpns+y4sspu+0rfJXwTorIuE=
  api: https://api.run.pivotal.io
  organization: vinsonchuong
  space: development
